#!/usr/bin/env bash
# superstition.
cur=1
while [ $cur -le 20 ]
do
	echo "$cur"

	if [ $cur = 4 ]
	then
		echo "bad luck from China"
	elif [ $cur = 9 ]
	then 
		echo "bad luck from Japan"
	elif [ $cur = 17 ]
	then
		echo "bad luck from Italy"
	fi
	((cur++))
done

