#!/usr/bin/env bash
# superstition.
cur=1
while [ $cur -le 20 ]
do
	echo "$cur"

	case $cur in
		4)
			echo "bad luck from China"
		;;
		9)
			echo "bad luck from Japan"
		;;
		17)
			echo "bad luck from Italy"
		;;
	esac
	
	((cur++))
done

