#!/usr/bin/env bash
# configure Nginx to to run as nginx user.

sed -i 's/user/user nginx/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;' /etc/nginx/sites-available
sed -i 's/listen [::]:80 default_server;/listen [::]:8080 default_server;' /etc/nginx/sites-available
